acchost:           http://192.168.20.103:9100
rshost:            http://192.168.20.102:12501
rsfhost:           http://192.168.20.102:12501
apihost:           http://192.168.20.102:12500
uchost:            http://192.168.20.103:30100
dochost:           http://192.168.20.111:2090
counterhost:       http://192.168.20.102:7788
onehost:           http://192.168.20.102:23200
ufophost:          http://192.168.20.102:12500/v1/ufop
username:          general_storage_001@test.qiniu.io
password:          QA@7niu.com
access_key:        7nTt8wUdtOQmJIVLsWqsJ3fjZ38buaHR5F5UNqrj
secret_key:        Fkc4wcqMmNJTb_99_1zjSrS9r44s0WutiBxvmhEB
admin_username:    root
admin_password:    root
admin_access_key:  4_odedBxmrAHiu4Y0Qp0HPG0NANCf6VAsAjWL_k9
admin_secret_key:  SrRuUVfDX6drVRvpyN8mv8Vcm9XnMZzlbDfvVfMe
bucket_username:   general_storage_002@test.qiniu.io
bucket_password:   QA@7niu.com
bucketaccess_key:  HwFOxpYCQU6oXoZXFOTh1mq5ZZig6Yyocgk3BTZZ
bucketsecret_key:  z8vEFQPl6RHyvOSS1UsAS2wOdY-Xn77v-LMbjAns
quota_username:    general_storage_004@test.qiniu.io
quota_password:    QA@7niu.com
quota_access_key:  Pwurmp0ygwJ-FcuJbX_5k42bQKe9XuVEyA9_yVBu
quota_secret_key:  41Xs_d9-R5J27LF7_39jfvodesOIQiYyl490nPKF
aksk_username:     general_storage_003@test.qiniu.io
aksk_password:     QA@7niu.com
multizone_ak:      Dms7hkkBa2EFszG4GT6sCNLGf7BSwsZX8eFdvdQ8
multizone_sk:      qfgbmr0Eqo1VVNNJOWJS7kb1AStUBF3XszfUYadw

# 与cd_z1不同的地方
iohost:            http://192.168.20.111
uphost:            http://192.168.20.103:5010
apigate_uphost:    http://192.168.20.103:3710

# 默认测试空间和Domain
bucket:            publicbucket_z0
